### PR TITLE
add 'Adaptive','Thermal heat losses chart' and 'SET output chart'

### PR DESCRIPTION
**Pull request by Yannnnnnny**
### **Description**
The ‘Adaptive’, ‘Thermal heat losses’, and ‘SET output’ charts is merged into the project and will not affect the existing program. Users can select the these charts in the dropdown box, then enter the corresponding parameters and select the wind speed. The charts on the right shows the corresponding visualization.
### **Type of change**

1. Adaptive chart:

- [x] Add Adaptive ASHRAE charts into the project, and combine Adaptive ASHRAE and EN into one function to simplify the code.
- [x] Under the Adaptive ASHRAE model, the charts will show the operating temperature, and comfort level, with different colors indicating different acceptability limits.
- [x] Change the show results of Adaptive charts, when temperature outside the comfort area, display prompt information.
- [x] SI&IP units conversion. 

2. Thermal heat losses chart

- [x] Add Thermal heat losses chart under pmv of ASHRAE model into the project. 
- [x] Under different input parameters, the charts show the corresponding visualization of ‘Water vapor diffusion through the skin’ and other ten types of heat loss values.
- [x] Realized the function of making the polyline disappear and appear by clicking the parameter name with the mouse.
- [x] SI&IP units conversion. 

3. SET outputs chart

- [x] Add SET outputs chart under pmv of ASHRAE model into the project. 
- [x] Set two y axes, and different broken lines correspond to different y values according to the definition.
- [x] When changing the input parameters such as Mean Radiant Temperature, the chart will display the corresponding visualization of ten output values such as ‘SET temperature’.
- [x]  Realized the function of making the polyline disappear and appear by clicking the parameter name with the mouse.
- [x]  SI&IP units conversion. 
### **Unit Test**
**1. Adaptive chart:**
User can select Adaptive ASHRAE model, and set inputs of air temperature, mean radiant temperature, prevailing mean outdoor temperature, and Air speed. The chart will generate the visualization. The chart size adapts to the current UI interface, and the color matches the interface tone.
image
When the calculated result of the input value exceeds the 80% or 90% comfort zone, the corresponding "too warm" or "too cool" will be displayed above the show result. 
image
image
Can manually select SI or IP unit.
image
The codes for Adaptive EN and Adaptive ASHRAE will be combined to simplify the code.
image
**2. Thermal heat losses chart:**
User can select ‘PMV-ASHRAE 55’ model, and select ‘Thermal heat losses vs. air temperature’ chart.
image
The user can enter the corresponding parameter value, and the chart will display the corresponding visual image. The chart size adapts to the current UI interface, and the color matches the interface tone. And in the function bar below the chart, users can display or hide some parameter lines by clicking the mouse.
image
Can manually select SI or IP unit.
image
**3. SET outputs chart**
User can select ‘PMV-ASHRAE 55’ model and select ‘SET outputs chart’.
image
The user can enter the corresponding parameter value, and the chart will display the corresponding visual image. The chart size adapts to the current UI interface, and the color matches the interface tone.
Different parameters will correspond to different y-axes.  And in the function bar below the chart, users can display or hide some parameter lines by clicking the mouse.
image
Can manually select SI or IP unit.
image

### **checklist**

- [x] The code has been formatted via black
- [x] The code has been test, which will not affect the current project version

### CODE REVIEW

**Review by karlliu666 — APPROVED** [review]
it is true that they did the three graph test

**Review by Marcusxixi — APPROVED** [review]
All function has been tested

**Review by Mitarashiharuto — APPROVED** [review]
Fix the bugs in chart

**Review by Ha02hen — COMMENTED** [review]
Good job on fixing the bugs in the chart

**Review by Ha02hen — APPROVED** [review]

**Comment by lja996877259** [comment]
Good job on do 3 chart

**Review by lja996877259 — APPROVED** [review]
Good job on 3 charts

**Review by jiadongZhangWorkIn — APPROVED** [review]
Added images and fixed some bugs,It looks good.

**Review by CharlieJiangJC — COMMENTED** [review]
All the changes are ok.

**Review by Jinjia-Bai — APPROVED** [review]

**Review by Echo11ovo — APPROVED** [review]
All good

**Comment by ZhouTongworking** [comment]
All function has been tested

**Comment by karlliu666** [comment]
The bug in all image has been fixed

**Review by karlliu666 — APPROVED** [review]

**Review by CharlieJiangJC — APPROVED** [review]
The code is ok.

**Review by Xuhui-Wang-9988 — COMMENTED** [review]
all issues be tested

**Review by Echo11ovo — APPROVED** [review]
All good, nice to see these changes

**Review by Ruixin126 — APPROVED** [review]

**Pull request merged**
