### PR TITLE
Add 'Psychrometric (air temperature)' chart in PMV ASHRAE/ PMV EN

### PR DESCRIPTION
**Pull request by Jinjia-Bai**
### Description
The 'Psychrometric (air temperature)' chart has been implemented in the default comfort model (PMV ASHRAE/PMV EN), and it can convert the display units as well as output the relevant data for the mouse hover position calculation. And after merging existing progress, it is tested that the current code is compatible.

### Type of changes
- [x] Added 'Psychrometric (air temperature)' charts into the project, and combine 'PMV ASHRAE' and 'PMV EN' into one function to simplify the code.
- [x] In the PMV ASHRAE model, the chart will show the 'Dry-bulb Temperature' against 'Humidity Ratio' with 'Relative Humidity' lines in 10% steps and comfort level.
- [x] In the PMV EN model, the chart will show the 'Dry-bulb Temperature' against 'Humidity Ratio' with 'Relative Humidity' lines in 10% steps and category level with different colors indicating different categories.
- [x] Change the show results of 'Psychrometric (air temperature)', when temperature outside the comfort area, display prompt information.
- [x] SI&IP units conversion.

### Unit Test
The user selects the "PMV-ASHRAE 55" model and the "Psychrometric (air temperature)" chart, then enters the values ​​of the parameters on the left hand input form. The visualization results are shown in the figure below. The output annotations will change according to the mouse hover position.
image
As shown above, the initial output of the annotation is entered and calculated by the red dot, and then it updated as the mouse moves in the picture below. Aside from this annotation, mouse hover events display no other information.
image
When the output text result shows '✘ Does not comply with ASHRAE Standard 55-2023', the red dot will be outside the blue area.
image
Turn on the IP unit conversion switch, and the corresponding values ​​and unit text in the chart will be converted accordingly.
image
Still select this chart, but switch to the PMV EN model, and the chart will be as shown below. The text result for categories correspond to the red dot in darker or lighter green areas.
image
The figure below shows the unit conversion between numerical values ​​and text when the IP unit switch is turned on. It is basically the same as this chart of the PMV ASHRAE model.
image
### checklist
- [x] The code has been formatted via black
- [x] The code has been test, which will not affect the current project version

### CODE REVIEW

**Review by lja996877259 — COMMENTED** [review]
Adding Psychrometric(air temperature) successfully without problems

**Comment by t-kramer** [comment]
Hi all, the edges of the comfort zones still look a bit 'wavy'. It would be great if you look into potential reasons for it and fix it. Otherwise, the charts look great. Well done!

**Comment by Jinjia-Bai** [comment]
> Hi all, the edges of the comfort zones still look a bit 'wavy'. It would be great if you look into potential reasons for it and fix it. Otherwise, the charts look great. Well done!

OK, I will try to fix it.

**Review by Mitarashiharuto — APPROVED** [review]
Fix the wavy lines in charts

**Review by karlliu666 — APPROVED** [review]

**Pull request merged**
