### PR TITLE
Chart change units should not move

### PR DESCRIPTION
**Pull request by Ruixin126**
# Adaptive EN, Adaptive Ashrae, PMV - EN, PMV-Ashrae charts bug fixing
Fixed the issue where the chart's content position remained unchanged when converting the X and Y axes from Celsius to Fahrenheit. Ensured that the data in the chart stays in the correct position after changing the unit of the axes.
## Type of change
- [x] Bug fixing

Make sure the chart in correct position after change the unit of axes in Adaptive EN
image
image

Make sure the chart in correct position after change the unit of axes in Adaptive Ashrae
image
image

Make sure the chart in correct position after change the unit of axes in PMV Ashrae
image
image

## Checklist

- [x] The code has been formatted via black

### CODE REVIEW

**Comment by Xuhui-Wang-9988** [comment]
nice change. from now now on the hover annotation should not remove during mouse moving anymore

**Review by Xuhui-Wang-9988 — APPROVED** [review]

**Comment by Yannnnnnny** [comment]
all good

**Review by Yannnnnnny — APPROVED** [review]

**Comment by ZhouTongworking** [comment]
all good

**Review by Marcusxixi — APPROVED** [review]
All good

**Review by jiadongZhangWorkIn — APPROVED** [review]
code looks fine

**Review by ZhouTongworking — APPROVED** [review]

**Pull request merged**
