### PR TITLE
Compare Function

### PR DESCRIPTION
**Pull request by Ruixin126**
# Compare Function Documentation

## Description

This version is based on last Friday's version and was developed without disrupting other team members' code. After discussions with the other group, **this version should replace the current version**. Additionally, some to-do list has been added to the code to facilitate the work of team members. In this version, we are also implementing the Compare section, which is introduce another set of parameters for comparison within the PMV - ASHRAE 55 model. The comparison will be also displayed in the Temperature vs. Relative Humidity chart.

## Type of change
- [x] Added an additional set of inputs in the Compare function.
- [x] Stored all inputs from the Compare page in Local Storage.
- [x] A new set of results will be displayed based on the new inputs.
- [x] In the Compare function under the PMV - ASHRAE 55 model, only three charts are available for selection.
- [x] A example function displayed in the top right corner of the chart.
- [x] Added numerous to-do lists in different files for improvements and bug fixes.
- [x] The default chart will be used for implementation and display with Plotly.
- [x] Fixed a bug in the chart that caused an error when chart displaying the range out of 10-40.

### This test was conducted by Zhou Tong, Ruixin Wu, and Xuhui Wang, Echo Shen:

The Compare Function has been tested with the following scenarios: 
### 1. Unit Test:
 - In Compare models, the Select chart function ensure only show 3 options.
image
 - Switching between Compare and Default modes across different models and charts to ensure no errors occur.
 - Inputs different values in Compare mode to verify correct output on the charts.
image
 - Inputs different values in Compare mode to verify correct output in the results.
image
 - Inputs different values in Compare mode to ensure that Local Storage can correctly track the inputs on the page.
image
 - A example function should displayed in the top right corner of the chart in both Default and compare function, this function will later introduce the functionality to display values based on the mouse position on the x and y axes of the chart.
image
 -  Make sure the default chart will be display with Plotly, return as a figure rather than a image.
image

### 2. Regression Tests:
 - Ensuring no disruption to other team members' code:
    - In Default models, ensure different models have different select chart options.
image
    - Inputs different values in in the Default mode of the PMV - ASHRAE 55 model to verify correct output on the charts.
image
    - Inputs different values in the Default mode of the PMV - ASHRAE 55 model to verify correct output in the results.
image
    - Inputs different values in the Default mode of the PMV - ASHRAE 55 model to ensure that Local Storage can correctly track the inputs on the page.
image

### 3. Bug Fixed :
- Ensure the chart that don't caused an error when chart displaying the range out of 10-40.
image

**Test Configuration**:

* Dash version: 2.17.1
* Python version: 3.11.6, 3.11.7
* Operating System: Windows 10, Windows 11
* Browser Type: Google Chrome, Edge

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit and regression tests pass locally with my changes

### CODE REVIEW

**Review by Echo11ovo — COMMENTED** [review]
fixed conflict

**Review by Echo11ovo — COMMENTED** [review]
Dealing with conflicts is a smart merge, which introduces new bugs to appea, need to roolback `main` branch version

**Comment by FedericoTartarini** [comment]
@Ruixin126 thank you for submitting this Pull request but you need to first fix the conflicts and they I will review it.

**Comment by Ruixin126** [comment]
@FedericoTartarini please check the slack and roll back to the Fridays version, the conflicts will be resolved.

**Comment by FedericoTartarini** [comment]
Can you please do that? If I rollback the version is going to create even more issue, wouldn't it?

**Comment by Ruixin126** [comment]
Seems we don't have permission to do that. The versions is showing more bugs now, thus we've decided to roll back.

**Comment by FedericoTartarini** [comment]
please check on Slack, I created a new branch called development and there there should be the right code. You will need to create a pull request to development

**Comment by Ruixin126** [comment]
Please check again, the code is request to merge to development

**Review by Mitarashiharuto — COMMENTED** [review]
Fix the issues of merging codes

**Review by FedericoTartarini — APPROVED** [review]

**Pull request merged**
