### PR TITLE
add all charts of EN&ASHRAE model and solve conflicts

### PR DESCRIPTION
**Pull request by Yannnnnnny**
1. add all basic chart of the ASHRAE and EN model
2. add mouse interaction of 'Psychrometric' and 'relative humidity vs temperature' charts of ASHRAE and EN model
3. add IP units of Adaptive of ASHRAE and EN model, 'relative humidity vs temperature' charts of PMV of ASHRAE and EN model, 'Thermal heat loss' and 'SET output' charts of PMV ASHRAE model.
4. fix conflicts

### CODE REVIEW

**Review by Mitarashiharuto — COMMENTED** [review]
Solve the conflicts of merging

**Comment by CharlieJiangJC** [comment]
The four points are basicly resolved.

**Review by CharlieJiangJC — APPROVED** [review]
The mergering parts are basicly completed.

**Comment by Ruixin126** [comment]
There are a lot of bugs in this version, and some code has broken, please make some tests before pull request.

**Pull request closed without merging**
