### PR TITLE
1. added 'Temperature VS Relative Humidity' chart in (PMV ASHRAE)/(PMV EN)/Compare; 2. added 'Air speed vs Operature Temperature' chart in PMV ASHRAE

### PR DESCRIPTION
**Pull request by CharlieJiangJC**
The ‘Temperature VS Relative Humidity’ and ‘Air speed vs Operature Temperature’ charts are merged into the project and will not affect the existing program. Users can select the these charts in the dropdown box, then enter the corresponding parameters. The charts on the right shows the corresponding visualization.
1. Temperature VS Relative Humidity:
- [ ] Added 'Temperature VS Relative Humidity' charts into the project, and combine 'PMV ASHRAE' and 'PMV EN' into one function to simplify the code.
- [x] In the PMV ASHRAE model, the chart will show the 'Relative Humidity', 'Dry-bulb Temperature' and comfort level.
- [x] In the PMV ASHRAE model, the chart can be compared now.
- [x] In the PMV EN model, the chart will show the 'Relative Humidity', 'Dry-bulb Temperature' and category level with different colors indicating different categories.
- [x] Change the show results of 'Temperature VS Relative Humidity', when temperature outside the comfort area, display prompt information.
- [x] SI&IP units conversion.

2. Air speed vs Operature Temperature:
- [x] Added 'Air speed vs. operative temperature' chart in PMV ASHRAE model into the project.
- [x] SI&IP units conversion.

Unit Test
1. 'Temperature VS Relative Humidity' chart in PMV ASHRAE model:
User can select 'PMV-ASHRAE 55' model, and set inputs of air temperature, mean radiant temperature, air speed, relative humidity, metabolic rate (met)and clothing level (clo). The chart will generate the visualization. The annotation will be generated and change the value based on the current mouse position. The chart size adapts to the current UI interface.
image
When the red dot outside the neutral sensation region, the corresponding '✘ Does not comply with ASHRAE Standard 55-2023' will be displayed above the show result.
image
Can manually select SI or IP unit:
image
In addition, I would like to point out a note: when the unit is switched to 'IP', the value of 'tdp' parameter in annotation should also be switched to the value corresponding to the degree Fahrenheit (this value is indeed inconsistent with the value of the original page, I think the original page is wrong).
image
The codes for PMV EN and PMV ASHRAE will be combined to simplify the code:
image

2. The compare of 'Temperature VS Relative Humidity' chart in PMV ASHRAE model:
User can select 'PMV ASHRAE' model, and set inputs of air temperature, mean radiant temperature, air speed, relative humidity, metabolic rate (met)and clothing level (clo). The chart will generate the visualization. The annotation will be generated and change the value based on the current mouse position. The chart size adapts to the current UI interface. The sensation will change based on the red dot position.
image
When the red dot outside the neutral sensation region, the corresponding '✘ Does not comply with ASHRAE Standard 55-2023' will be displayed above the show result.
image
Can manually select SI or IP unit:
image
In addition, the value of 'tdp' parameter in annotation is also indeed inconsistent with the value of the original page, I think the original page is wrong:
image

3. 'Temperature VS Relative Humidity' chart in PMV EN model:
User can select 'PMV EN' model, and set inputs of air temperature, mean radiant temperature, air speed, relative humidity, metabolic rate (met)and clothing level (clo). The chart will generate the visualization. The annotation will be generated and change the value based on the current mouse position. The chart size adapts to the current UI interface. The category value will change based on the red dot position.
image
image
image
when the red dot outside moves to the category IV region, the corresponding '✘ Does not comply with EN-16798' will be displayed above the show result.
image
Can manually select SI or IP unit:
image
In addition, the value of 'tdp' parameter in annotation is also indeed inconsistent with the value of the original page, I think the original page is wrong:
image

4. 'Air speed vs Operature Temperature' chart:
User can select PMV-ASHRAE 55 model and select ‘Air speed vs. Operative temperature’
image
The input field on the left has the initial values and as the user enters the values, the visualization on the right changes accordingly
image
The user can also make input of different units by switching units, and the corresponding chart will also change
image

### CODE REVIEW

**Review by lja996877259 — APPROVED** [review]

**Comment by t-kramer** [comment]
Styling-wise, I am mostly fine with the these graphs. However, for the PMV charts I would try to find another solution for the annotated values for temperature, relative humidity etc. in the upper right corner. Maybe you can add a rectangular, slightly transparent background for this 'textbox', so the separation between text and the grid lines is clearer. Also, if you keep this textbox on the right of the graph, I'd also align the text to the right edge of the figure.

**Comment by FedericoTartarini** [comment]
* fit the calculation of the wind speed chart using pytc and brentq solver

**Comment by Marcusxixi** [comment]
I reviewed your code, and overall, you've done a good job with the visual aspects. The interface closely matches the original site, which is great.

However, I did notice that some parts of the interaction aren't as smooth as expected. 
Specifically:  

1. when moving the mouse over the chart, the values in the top right corner update a bit slowly, and there's a noticeable lag.
image

2. With the same input values, both the output results and the chart results are slightly inconsistent when compared to the original website. It seems that there might be some discrepancies in the calculations or display.
81ab98bc5695712ae89d99e9c34b589

3. When I toggle the 'SI Units' switch, the input values sometimes become strange or unexpected. It seems like there might be an issue with how the input fields handle toggling.
851c66816211fa206bb208a41c6c1e3

4. Where an error occurs occasionally when interacting with the hover functionality in the graph.
image

**Comment by Marcusxixi** [comment]
I reviewed your code, and overall, you've done a good job with the visual aspects. The interface closely matches the original site, which is great.

However, I did notice that some parts of the interaction aren't as smooth as expected.

Specifically:
1. When moving the mouse over the chart, the values in the top right corner update a bit slowly, and there's a noticeable lag.
image

2. With the same input values, both the output results and the chart results are slightly inconsistent when compared to the original website. It seems that there might be some discrepancies in the calculations or display.
81ab98bc5695712ae89d99e9c34b589

3. When I toggle the 'SI Units' switch, the input values sometimes become strange or unexpected. It seems like there might be an issue with how the input fields handle toggling.
b91618b9fee7669d9072954baa48014

4. Where an error occurs occasionally when interacting with the hover functionality in the graph.
39b81513760b233fe64581e3202ece5

**Pull request closed without merging**
